services:
  - type: web
    name: streamlit-rag-application
    runtime: docker
    plan: free
    branch: dev
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
